version: '3'
services:

  kafka_builder:
    image: ${DOCKER_IMAGE}:${DOCKER_IMAGE_VERSION}-${KAFKA_VERSION}
    build: 
      context: docker/
      args:
        - KAFKA_VERSION
        - SCALA_VERSION

    command: bash  
    
     




