version: '3'
services:

  kafka:
    image: mcano/kafka:v1.0-0.10.2.0
    env_file:
      - config/kafka.properties
    ports:
      - 9092:9092
    #command: bash  -c "bash start-kafka.sh && cat $$KAFKA_HOME/config/server.properties && env |grep -i kafka " 
    networks: 
      - kafka-net
    depends_on:
      - zookeeper
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
      restart_policy:
        condition: on-failure
  
  zookeeper:
    image: zookeeper:3.4
    ports:
     - 2181:2181
    networks:
      - kafka-net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure

  
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - kafka-net


networks:
  kafka-net: