version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka-1:
    image: confluent/kafka-marcos:1.0
    volumes:
      - ./bin/kafka_2.11-0.10.2.0/:/kafka
    command: ["/kafka/bin/kafka-server-start.sh" ,"/kafka/config/server.properties"]


  kafka-2:
    image: confluent/kafka-marcos:1.0
    volumes:
      - ./bin/kafka_2.11-0.10.2.0/:/kafka
    command: ["/kafka/bin/kafka-server-start.sh" ,"/kafka/config/server2.properties"]

