version: '3'
services:

  kafka:
    image: ${DOCKER_IMAGE}:${DOCKER_IMAGE_VERSION}-${KAFKA_VERSION}
    env_file:
      - config/kafka.properties
    ports:
      - 9092:9092
    command: bash  -c "bash start-kafka.sh && cat $$KAFKA_HOME/config/server.properties && env |grep -i kafka " 
    networks: 
      - kafka-net
    
  zookeeper:
    image: zookeeper:3.4
    ports:
     - 2181:2181
    networks:
      - kafka-net


networks:
  kafka-net: