version: '3'
services:

  kafka: &kafka
    image: mcano/kafka:v1.0.0-0.10.2.0
    #image: confluentinc/cp-kafka:3.2.2-1
    ports:
      - 9092
    environment: 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$${HOSTNAME}:9092
      # by default image will assign -1 as broker id
      #KAFKA_BROKER_ID: -1 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_TIMEOUT_MS: 500
      KAFKA_DELETE_TOPIC_ENABLED: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLED: "true"
      JMX_PORT: 9999
      KAFKA_CREATE_TOPICS: DEVICE_EVENTS:1:1,DECORATED_DEVICE_EVENTS:1:1,DECORATED_DEVICE_EVENTS_SORTED_PER_DEVICE:1:1

    networks: 
      - kafka-simple-network
    depends_on:
      - zookeeper
    command: bootstrap.sh

  zookeeper:
    image: zookeeper:3.4
    ports:
     - 2181:2181
    environment:
      - ZOO_TICK_TIME=4000
    networks:
      - kafka-simple-network

  kafka-rest:
    image: confluentinc/cp-kafka-rest:3.2.2
    ports:
      - 8082:8082
    networks:
      - kafka-stack-network
    environment:
      - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper
      - KAFKA_REST_ID=1
      - KAFKA_REST_LISTENERS=http://0.0.0.0:8082/
      - KAFKA_REST_HOST_NAME=kafka-rest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - zookeeper
      - kafka

networks:
  kafka-simple-network: