version: '3'
services:

  kafka: &kafka
    image: mcano/kafka:v0.0.0-0.10.2.0
    #image: confluentinc/cp-kafka:3.2.2-1
    ports:
      - 9092:9092
    environment: 
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$${HOSTNAME}:9092
      #KAFKA_BROKER_ID: -1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_TIMEOUT_MS: 500
      KAFKA_DELETE_TOPIC_ENABLED: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLED: "true"
      JMX_PORT: 9999
      KAFKA_CREATE_TOPICS: DEVICE_EVENTS:1:1,DECORATED_DEVICE_EVENTS:1:1,DECORATED_DEVICE_EVENTS_SORTED_PER_DEVICE:1:1

    networks: 
      - kafka-simple-network
    depends_on:
      - zookeeper
    command: bootstrap.sh

  zookeeper:
    image: zookeeper:3.4
    ports:
     - 2181:2181
    environment:
      - ZOO_TICK_TIME=4000
    networks:
      - kafka-simple-network

networks:
  kafka-simple-network: